FROM nginx:latest

COPY default.conf /etc/nginx/conf.d

RUN mkdir /etc/nginx/ssl

COPY cert.crt /etc/nginx/ssl

COPY cert.key /etc/nginx/ssl

COPY cert2.crt /etc/nginx/ssl

COPY cert2.key /etc/nginx/ssl

RUN chown -R root:root /etc/nginx/ssl

RUN chmod -R 600 /etc/nginx/ssl
